### PR TITLE
Skip gems in RSpec integration

### PR DESCRIPTION
**Pull request by alexevanczuk**

### CODE REVIEW

**Review by ngan — APPROVED** [review]
Thanks

**Comment by iMacTia** [comment]
This change just surprised me.
We're in the process of isolating some of the application code into "gems", but right now the coupling between these and the rest of the codebase is pretty high, and we need to reduce it before we can properly isolate the code into a standalone gem.

Until then, the gems are effectively part of the monolith, and as such we'd like to run tests for it.
Before this change, moving files into gems and their tests would have no major repercussions as tests would be run anyway.

But after this change, how are we supposed to correctly run tests for our gems?

**Comment by alexevanczuk** [comment]
@iMacTia We chatted a bit about this one and I'm wondering if you really need to have a `.gemspec` for these systems. I don't know if I'd call something a gem if they aren't published/distributed, aren't tested in isolation, and only run in the context of the monolith, even if it has a gemspec.

Is there some gem-related feature you're getting right now that you rely on? If not, have you considered just moving that code into a pack until it's ready to be a fully-fledged gem that has its tests run in isolation?

**Comment by iMacTia** [comment]
Thanks @alexevanczuk, I completely get what you're saying and I realise what we're trying to do is not very "purist" 😅.
I guess we're trying to make this packages into some sort of thing-in-between a gem and a package.
But you're right this does not have tangible benefits and we could find other workarounds.

I guess the choice is on our side to either revert them back to simple packages (and note gem dependencies somewhere else, as you suggested) or to go all-in with the gem idea, meaning they should be bundled and tested in isolation to ensure the `gemspec` is correct.

I'll discuss this one with the team and we'll decide how to proceed, thank you for taking the time to explain your reasoning

**Pull request merged**
